#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaskManagerAndroid.Resource", IsApplication=true)]

namespace TaskManagerAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int status_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addComment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int addLogwork = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int comments = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int editTask = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logworks = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menu = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int task = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int taskDetails = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tasksList = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int user = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int users = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001f
			public const int adminEdit = 2131165215;
			
			// aapt resource value: 0x7f070016
			public const int cancelTask = 2131165206;
			
			// aapt resource value: 0x7f070022
			public const int cancelUser = 2131165218;
			
			// aapt resource value: 0x7f070002
			public const int commentEdit = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int commentLabel = 2131165185;
			
			// aapt resource value: 0x7f070015
			public const int commentsTask = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int createComment = 2131165184;
			
			// aapt resource value: 0x7f070024
			public const int createLogwork = 2131165220;
			
			// aapt resource value: 0x7f070035
			public const int createTask = 2131165237;
			
			// aapt resource value: 0x7f070037
			public const int createUser = 2131165239;
			
			// aapt resource value: 0x7f070031
			public const int createdDateDetails = 2131165233;
			
			// aapt resource value: 0x7f070033
			public const int creatorDetails = 2131165235;
			
			// aapt resource value: 0x7f070012
			public const int deleteTask = 2131165202;
			
			// aapt resource value: 0x7f070021
			public const int deleteUser = 2131165217;
			
			// aapt resource value: 0x7f07002e
			public const int descriptionDetails = 2131165230;
			
			// aapt resource value: 0x7f07000a
			public const int descriptionEdit = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int descriptionLabel = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int detailsTask = 2131165203;
			
			// aapt resource value: 0x7f070023
			public const int errorsEditUser = 2131165219;
			
			// aapt resource value: 0x7f07001c
			public const int firstNameEdit = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int firstNameLabel = 2131165211;
			
			// aapt resource value: 0x7f070032
			public const int lastEditDateDetails = 2131165234;
			
			// aapt resource value: 0x7f07001e
			public const int lastNameEdit = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int lastNameLabel = 2131165213;
			
			// aapt resource value: 0x7f070028
			public const int login = 2131165224;
			
			// aapt resource value: 0x7f070005
			public const int logworkEdit = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int logworkLabel = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int logworksTask = 2131165204;
			
			// aapt resource value: 0x7f070027
			public const int password = 2131165223;
			
			// aapt resource value: 0x7f07001a
			public const int passwordEdit = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int passwordLabel = 2131165209;
			
			// aapt resource value: 0x7f070029
			public const int register = 2131165225;
			
			// aapt resource value: 0x7f070034
			public const int responsibleDetails = 2131165236;
			
			// aapt resource value: 0x7f07000e
			public const int responsibleEdit = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int responsibleLabel = 2131165197;
			
			// aapt resource value: 0x7f07002a
			public const int result = 2131165226;
			
			// aapt resource value: 0x7f070003
			public const int saveComment = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int saveLogwork = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int saveTask = 2131165201;
			
			// aapt resource value: 0x7f070020
			public const int saveUser = 2131165216;
			
			// aapt resource value: 0x7f070030
			public const int statusDetails = 2131165232;
			
			// aapt resource value: 0x7f070010
			public const int statusEdit = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int statusLabel = 2131165199;
			
			// aapt resource value: 0x7f07002c
			public const int tasksMenu = 2131165228;
			
			// aapt resource value: 0x7f070025
			public const int textView1 = 2131165221;
			
			// aapt resource value: 0x7f07002d
			public const int titleDetails = 2131165229;
			
			// aapt resource value: 0x7f070008
			public const int titleEdit = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int titleLabel = 2131165191;
			
			// aapt resource value: 0x7f070036
			public const int toolbar = 2131165238;
			
			// aapt resource value: 0x7f070026
			public const int username = 2131165222;
			
			// aapt resource value: 0x7f070018
			public const int usernameEdit = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int usernameLabel = 2131165207;
			
			// aapt resource value: 0x7f07002b
			public const int usersMenu = 2131165227;
			
			// aapt resource value: 0x7f07002f
			public const int workingHoursDetails = 2131165231;
			
			// aapt resource value: 0x7f07000c
			public const int workingHoursEdit = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int workingHoursLabel = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Comments = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateComment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateLogwork = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditTask = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditUser = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Logworks = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TaskDetails = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Tasks = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int toolbar = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Users = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int status_prompt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
