//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace TaskManagerApiWCF.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/TaskManagerApiWCF.Models")]
    public partial class UserModel : TaskManagerApiWCF.Models.BaseModel
    {
        
        private string FirstNameField;
        
        private bool IsAdminField;
        
        private string LastNameField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin
        {
            get
            {
                return this.IsAdminField;
            }
            set
            {
                this.IsAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/TaskManagerApiWCF.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TaskManagerApiWCF.Models.UserModel))]
    public partial class BaseModel : object
    {
        
        private int IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBaseServicesOf_UserModel")]
public interface IBaseServicesOf_UserModel
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBaseServicesOf_UserModel/GetAll", ReplyAction="http://tempuri.org/IBaseServicesOf_UserModel/GetAllResponse")]
    System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState);
    
    TaskManagerApiWCF.Models.UserModel[] EndGetAll(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBaseServicesOf_UserModel/GetByID", ReplyAction="http://tempuri.org/IBaseServicesOf_UserModel/GetByIDResponse")]
    System.IAsyncResult BeginGetByID(int id, System.AsyncCallback callback, object asyncState);
    
    TaskManagerApiWCF.Models.UserModel EndGetByID(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBaseServicesOf_UserModel/Save", ReplyAction="http://tempuri.org/IBaseServicesOf_UserModel/SaveResponse")]
    System.IAsyncResult BeginSave(TaskManagerApiWCF.Models.UserModel entity, System.AsyncCallback callback, object asyncState);
    
    void EndSave(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBaseServicesOf_UserModel/Delete", ReplyAction="http://tempuri.org/IBaseServicesOf_UserModel/DeleteResponse")]
    System.IAsyncResult BeginDelete(TaskManagerApiWCF.Models.UserModel entity, System.AsyncCallback callback, object asyncState);
    
    void EndDelete(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBaseServicesOf_UserModelChannel : IBaseServicesOf_UserModel, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public TaskManagerApiWCF.Models.UserModel[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((TaskManagerApiWCF.Models.UserModel[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetUserByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetUserByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public TaskManagerApiWCF.Models.UserModel Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((TaskManagerApiWCF.Models.UserModel)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BaseServicesOf_UserModelClient : System.ServiceModel.ClientBase<IBaseServicesOf_UserModel>, IBaseServicesOf_UserModel
{
    
    private BeginOperationDelegate onBeginGetAllDelegate;
    
    private EndOperationDelegate onEndGetAllDelegate;
    
    private System.Threading.SendOrPostCallback onGetAllCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetByIDDelegate;
    
    private EndOperationDelegate onEndGetByIDDelegate;
    
    private System.Threading.SendOrPostCallback onGetByIDCompletedDelegate;
    
    private BeginOperationDelegate onBeginSaveDelegate;
    
    private EndOperationDelegate onEndSaveDelegate;
    
    private System.Threading.SendOrPostCallback onSaveCompletedDelegate;
    
    private BeginOperationDelegate onBeginDeleteDelegate;
    
    private EndOperationDelegate onEndDeleteDelegate;
    
    private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public BaseServicesOf_UserModelClient()
    {
    }
    
    public BaseServicesOf_UserModelClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BaseServicesOf_UserModelClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BaseServicesOf_UserModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BaseServicesOf_UserModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetAllUsersCompletedEventArgs> GetAllUsersCompleted;
    
    public event System.EventHandler<GetUserByIDCompletedEventArgs> GetUserByIDCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBaseServicesOf_UserModel.BeginGetAll(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAll(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TaskManagerApiWCF.Models.UserModel[] IBaseServicesOf_UserModel.EndGetAll(System.IAsyncResult result)
    {
        return base.Channel.EndGetAll(result);
    }
    
    private System.IAsyncResult OnBeginGetAll(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IBaseServicesOf_UserModel)(this)).BeginGetAll(callback, asyncState);
    }
    
    private object[] OnEndGetAll(System.IAsyncResult result)
    {
        TaskManagerApiWCF.Models.UserModel[] retVal = ((IBaseServicesOf_UserModel)(this)).EndGetAll(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAllCompleted(object state)
    {
        if ((this.GetAllUsersCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAllUsersCompleted(this, new GetAllUsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAllAsync()
    {
        this.GetAllAsync(null);
    }
    
    public void GetAllAsync(object userState)
    {
        if ((this.onBeginGetAllDelegate == null))
        {
            this.onBeginGetAllDelegate = new BeginOperationDelegate(this.OnBeginGetAll);
        }
        if ((this.onEndGetAllDelegate == null))
        {
            this.onEndGetAllDelegate = new EndOperationDelegate(this.OnEndGetAll);
        }
        if ((this.onGetAllCompletedDelegate == null))
        {
            this.onGetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCompleted);
        }
        base.InvokeAsync(this.onBeginGetAllDelegate, null, this.onEndGetAllDelegate, this.onGetAllCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBaseServicesOf_UserModel.BeginGetByID(int id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetByID(id, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TaskManagerApiWCF.Models.UserModel IBaseServicesOf_UserModel.EndGetByID(System.IAsyncResult result)
    {
        return base.Channel.EndGetByID(result);
    }
    
    private System.IAsyncResult OnBeginGetByID(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int id = ((int)(inValues[0]));
        return ((IBaseServicesOf_UserModel)(this)).BeginGetByID(id, callback, asyncState);
    }
    
    private object[] OnEndGetByID(System.IAsyncResult result)
    {
        TaskManagerApiWCF.Models.UserModel retVal = ((IBaseServicesOf_UserModel)(this)).EndGetByID(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetByIDCompleted(object state)
    {
        if ((this.GetUserByIDCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetUserByIDCompleted(this, new GetUserByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetByIDAsync(int id)
    {
        this.GetByIDAsync(id, null);
    }
    
    public void GetByIDAsync(int id, object userState)
    {
        if ((this.onBeginGetByIDDelegate == null))
        {
            this.onBeginGetByIDDelegate = new BeginOperationDelegate(this.OnBeginGetByID);
        }
        if ((this.onEndGetByIDDelegate == null))
        {
            this.onEndGetByIDDelegate = new EndOperationDelegate(this.OnEndGetByID);
        }
        if ((this.onGetByIDCompletedDelegate == null))
        {
            this.onGetByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByIDCompleted);
        }
        base.InvokeAsync(this.onBeginGetByIDDelegate, new object[] {
                    id}, this.onEndGetByIDDelegate, this.onGetByIDCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBaseServicesOf_UserModel.BeginSave(TaskManagerApiWCF.Models.UserModel entity, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSave(entity, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IBaseServicesOf_UserModel.EndSave(System.IAsyncResult result)
    {
        base.Channel.EndSave(result);
    }
    
    private System.IAsyncResult OnBeginSave(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        TaskManagerApiWCF.Models.UserModel entity = ((TaskManagerApiWCF.Models.UserModel)(inValues[0]));
        return ((IBaseServicesOf_UserModel)(this)).BeginSave(entity, callback, asyncState);
    }
    
    private object[] OnEndSave(System.IAsyncResult result)
    {
        ((IBaseServicesOf_UserModel)(this)).EndSave(result);
        return null;
    }
    
    private void OnSaveCompleted(object state)
    {
        if ((this.SaveCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.SaveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void SaveAsync(TaskManagerApiWCF.Models.UserModel entity)
    {
        this.SaveAsync(entity, null);
    }
    
    public void SaveAsync(TaskManagerApiWCF.Models.UserModel entity, object userState)
    {
        if ((this.onBeginSaveDelegate == null))
        {
            this.onBeginSaveDelegate = new BeginOperationDelegate(this.OnBeginSave);
        }
        if ((this.onEndSaveDelegate == null))
        {
            this.onEndSaveDelegate = new EndOperationDelegate(this.OnEndSave);
        }
        if ((this.onSaveCompletedDelegate == null))
        {
            this.onSaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCompleted);
        }
        base.InvokeAsync(this.onBeginSaveDelegate, new object[] {
                    entity}, this.onEndSaveDelegate, this.onSaveCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBaseServicesOf_UserModel.BeginDelete(TaskManagerApiWCF.Models.UserModel entity, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDelete(entity, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IBaseServicesOf_UserModel.EndDelete(System.IAsyncResult result)
    {
        base.Channel.EndDelete(result);
    }
    
    private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        TaskManagerApiWCF.Models.UserModel entity = ((TaskManagerApiWCF.Models.UserModel)(inValues[0]));
        return ((IBaseServicesOf_UserModel)(this)).BeginDelete(entity, callback, asyncState);
    }
    
    private object[] OnEndDelete(System.IAsyncResult result)
    {
        ((IBaseServicesOf_UserModel)(this)).EndDelete(result);
        return null;
    }
    
    private void OnDeleteCompleted(object state)
    {
        if ((this.DeleteCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void DeleteAsync(TaskManagerApiWCF.Models.UserModel entity)
    {
        this.DeleteAsync(entity, null);
    }
    
    public void DeleteAsync(TaskManagerApiWCF.Models.UserModel entity, object userState)
    {
        if ((this.onBeginDeleteDelegate == null))
        {
            this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
        }
        if ((this.onEndDeleteDelegate == null))
        {
            this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
        }
        if ((this.onDeleteCompletedDelegate == null))
        {
            this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
        }
        base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                    entity}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IBaseServicesOf_UserModel CreateChannel()
    {
        return new BaseServicesOf_UserModelClientChannel(this);
    }
    
    private class BaseServicesOf_UserModelClientChannel : ChannelBase<IBaseServicesOf_UserModel>, IBaseServicesOf_UserModel
    {
        
        public BaseServicesOf_UserModelClientChannel(System.ServiceModel.ClientBase<IBaseServicesOf_UserModel> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetAll", _args, callback, asyncState);
            return _result;
        }
        
        public TaskManagerApiWCF.Models.UserModel[] EndGetAll(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            TaskManagerApiWCF.Models.UserModel[] _result = ((TaskManagerApiWCF.Models.UserModel[])(base.EndInvoke("GetAll", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetByID(int id, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = id;
            System.IAsyncResult _result = base.BeginInvoke("GetByID", _args, callback, asyncState);
            return _result;
        }
        
        public TaskManagerApiWCF.Models.UserModel EndGetByID(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            TaskManagerApiWCF.Models.UserModel _result = ((TaskManagerApiWCF.Models.UserModel)(base.EndInvoke("GetByID", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginSave(TaskManagerApiWCF.Models.UserModel entity, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = entity;
            System.IAsyncResult _result = base.BeginInvoke("Save", _args, callback, asyncState);
            return _result;
        }
        
        public void EndSave(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("Save", _args, result);
        }
        
        public System.IAsyncResult BeginDelete(TaskManagerApiWCF.Models.UserModel entity, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = entity;
            System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
            return _result;
        }
        
        public void EndDelete(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("Delete", _args, result);
        }
    }
}
